project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('writecloud.urls', 'writecloud'), namespace='writecloud'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

writecloud/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(r'', views.user_login, name='login'),
    path('signup/', views.sign_up, name='signup'),
    path('home/', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('account/', views.account, name='account'),
    path('story/<uuid:story_uuid>', views.story, name='story'),
    path('continue/', views.continue_story, name='continue_story'),
    path('top/', views.top_stories, name='top_stories'),
    path('contact/', views.contact, name='contact'),
    path('create/', views.create, name='create_story'),
]

writecloud/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid


# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('user_detail', kwargs={'pk': self.pk})


class Story(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    title = models.CharField(max_length=30)
    counter = models.IntegerField(default=0)
    subtitle = models.CharField(max_length=60, default="")
    length = models.PositiveSmallIntegerField()
    template = models.IntegerField(
        default=1,
        validators=[MaxValueValidator(4), MinValueValidator(1)]
    )
    include_images = models.BooleanField(default=False)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='stories')

    class Meta:
        verbose_name = 'story'
        verbose_name_plural = 'stories'

    def __str__(self):
        return f"{self.author}'s \"{self.title}\""

    def get_absolute_url(self):
        return reverse('story_detail', kwargs={'pk': self.pk})


class Page(models.Model):
    number = models.IntegerField()
    content = models.TextField(default="")
    image = models.ImageField(default=None)

    story = models.ForeignKey('Story', on_delete=models.CASCADE, related_name='pages')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='pages')

    # Each user can only have one page per story
    class Meta:
        verbose_name = 'page'
        verbose_name_plural = 'pages'
        constraints = [
            models.UniqueConstraint(
                name='unique_story_author_page',
                fields=['story', 'author']
            ),
        ]

    def __str__(self):
        return f"{self.story} page {self.number} by {self.author}"

    def get_absolute_url(self):
        return reverse('page_detail', kwargs={'pk': self.pk})


class Review(models.Model):
    stars = models.IntegerField()
    body = models.TextField(default="")

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')
    story = models.ForeignKey('Story', on_delete=models.CASCADE, related_name='reviews')

    # Each user can only have one review per story
    class Meta:
        verbose_name = 'review'
        verbose_name_plural = 'reviews'
        constraints = [
            models.UniqueConstraint(
                name='unique_author_story_review',
                fields=['author', 'story']
            ),
        ]

    def __str__(self):
        return f"{self.story} reviewed by {self.author}"

    def get_absolute_url(self):
        return reverse('review_detail', kwargs={'pk': self.pk})

writecloud/forms.py
from django import forms
from .models import *


# Form for reviewing a story
class ReviewForm(forms.ModelForm):

    stars = forms.IntegerField(widget=forms.RadioSelect(choices=[(i, i) for i in range(1, 6)]))
    body = forms.CharField(widget=forms.Textarea)

    author = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())
    story = forms.ModelChoiceField(queryset=Story.objects.all(), widget=forms.HiddenInput())

    class Meta:
        model = Review
        fields = ('stars', 'body', 'author', 'story')

class UserAccountForm(forms.ModelForm):
    UserProfile = ('user_account', 'selected_user', 'form')

writecloud/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Count, Avg, F
from django.views.decorators.csrf import csrf_exempt

from writecloud.models import Story, UserProfile
from django.contrib.auth.models import User

from .forms import *


# Create your views here.

@login_required
def index(request):
    # Get all stories
    stories = Story.objects.all()
    context = {
        'total_stories': Story.objects.count(),
        'total_users': User.objects.count(),
        'stories': [],
    }

    # Loop stories and get top 5 most commented
    for story in stories:
        review = story.reviews.all()
        stars = review.aggregate(Avg('stars'))['stars__avg']

        story_dict = {
            'uuid': story.uuid,
            'title': story.title,
            'stars': str(stars)[:1],
            'total_reviews': int(Review.objects.filter(story=story).count()),
        }

        # Only attach completed stories
        completed_pages = Page.objects.filter(story=story).count()
        if completed_pages == story.length:
            context['stories'].append(story_dict)

    def get_my_key(obj):
        return obj['total_reviews']

    # Display up to 5 top stories
    context['stories'].sort(key=get_my_key, reverse=True)
    context['stories'] = context['stories'][:5]
    return render(request, 'writecloud/index.html', context=context)


def contact(request):
    return render(request, 'writecloud/contact.html')


@login_required
def account(request):
    context = {
        'name': request.user,
        'stories': [],
    }

    # Loop stories and get only stories which current user has contributed to
    stories = Story.objects.all()
    for story in stories:
        story_dict = {
            'uuid': story.uuid,
            'title': story.title,
            'length': story.length,
            'initial_author': story.author,
        }

        # Only attach story with an author current user
        user_in_story = Page.objects.filter(author=request.user, story=story)
        if not user_in_story:
            pass
        else:
            context['stories'].append(story_dict)

    return render(request, 'writecloud/account.html', context=context)


def sign_up(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if not User.objects.filter(username=username).exists():
            user = User.objects.create_user(username=username, email=None, password=password)
            user.save()
            login(request, user)
            return redirect(reverse('writecloud:index'))
        else:
            return render(request, 'writecloud/signup.html', context={'fail': True})
    else:
        return render(request, 'writecloud/signup.html', context={'fail': False})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('writecloud:index'))

            else:
                return render(request, 'writecloud/login.html', context={'disabled': True, 'fail': False})

        else:
            return render(request, 'writecloud/login.html', context={'disabled': False, 'fail': True})

    else:
        return render(request, 'writecloud/login.html', context={'disabled': False, 'fail': False})


def user_logout(request):
    logout(request)
    return redirect(reverse('writecloud:login'))


@login_required
def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        subtitle = request.POST.get('subtitle')
        length = request.POST.get('length')
        template = 1
        include_images = False
        # Get the selected template or continue with first template
        if request.POST.get('template2') == '✓':
            template = 2
        if request.POST.get('template3') == '✓':
            template = 3
        if request.POST.get('template4') == '✓':
            template = 4
        if request.POST.get('include_images') == 'Images Included':
            include_images = True
        new_story = Story.objects.create(title=title, subtitle=subtitle, length=length, author=request.user,
                                         template=template,
                                         include_images=include_images)
        return HttpResponseRedirect(reverse('writecloud:story', kwargs={'story_uuid': new_story.uuid}))
    return render(request, 'writecloud/createStory.html')


@login_required
def story(request, story_uuid):
    # get the story for the requested UUID or redirect to a 404 page
    story = get_object_or_404(Story, pk=story_uuid)

    pages = story.pages.all()
    reviews = story.reviews.all()
    stars = reviews.aggregate(Avg('stars'))['stars__avg']
    total = reviews.aggregate(Count('stars'))['stars__count']

    # initialise the context dictionary to pass to the template
    # "None" fields will be overwritten if meaningful
    context_dict = {
        'uuid': story.uuid,
        'title': story.title,
        'subtitle': story.subtitle,
        'author': story.author,
        'total_pages': story.length,
        'pages': [],
        'counter': story.counter,
        'stars': str(stars)[:4],
        'total': total,
        'include_images': story.include_images,
        'template': story.template,
        'user_authenticated': None,
        'user_review': {
            'present': None,
            'stars': None,
            'body': None,
        },
        'reviews': [],
    }

    # unpack all pages of this story for display
    for page in pages:
        page_dict = {
            'number': page.number,
            'author': page.author,
            'content': page.content,
            'image': page.image,
        }
        context_dict['pages'].append(page_dict)

    # if the user is logged in...
    user_authenticated = request.user.is_authenticated
    if user_authenticated:

        context_dict.update({
            'user_authenticated': True,
        })

        # ...and has already rated this story:
        if reviews.filter(author=request.user).exists():

            # store their review separately from the others to display it first
            user_review = reviews.get(author=request.user)
            context_dict.update({
                'user_review': {
                    'present': True,
                    'stars': user_review.stars,
                    'body': user_review.body,
                }
            })
            reviews = reviews.exclude(author=request.user)

        # ...but has not rated this story yet:
        else:

            # if the request is POST, validate and save the form
            if request.method == 'POST':
                if 'rightClick' in request.POST:
                    story.counter = F('counter') + 1
                    story.save(update_fields=["counter"])
                    context_dict.update({
                        'counter': story.counter,
                    })
                    return HttpResponseRedirect(reverse('writecloud:story', kwargs={'story_uuid': story_uuid}))
                if 'leftClick' in request.POST:
                    story.counter = F('counter') - 1
                    story.save(update_fields=["counter"])
                    context_dict.update({
                        'counter': story.counter,
                    })
                    return HttpResponseRedirect(reverse('writecloud:story', kwargs={'story_uuid': story_uuid}))
                if 'voteForm' in request.POST:
                    body = request.POST.get('review')
                    stars = request.POST.get('rate')
                    Review.objects.create(body=body, stars=stars,
                                          author=request.user,
                                          story=story)
                else:
                    number = request.POST.get('number')
                    image = request.FILES.get('image')
                    content = request.POST.get('content')

                    Page.objects.create(number=number, content=content,
                                        image=image,
                                        story=story, author=request.user)
                    return HttpResponseRedirect(reverse('writecloud:story', kwargs={'story_uuid': story_uuid}))


            # if the request is GET, pass them the default bound form
            else:
                form = ReviewForm({
                    'author': request.user,
                    'story': story,
                })

                context_dict.update({
                    'form': form,
                })

    # if the user is not logged in:
    else:

        # set the flags to show them a login link
        context_dict.update({
            'user_authenticated': False,
            'user_review': {
                'present': False,
            }
        })

    # unpack all reviews to this story for display
    for review in reviews:
        review_dict = {
            'stars': review.stars,
            'body': review.body,
            'author': review.author,
        }
        context_dict['reviews'].append(review_dict)

    return render(request, 'writecloud/story.html', context=context_dict)


@login_required
def top_stories(request):
    stories = Story.objects.all()
    context = {
        'stories': [],
    }

    for story in stories:
        review = story.reviews.all()
        stars = review.aggregate(Avg('stars'))['stars__avg']

        story_dict = {
            'uuid': story.uuid,

templates/writecloud/base.html
<!DOCTYPE html>

{% load static %}

<style>
img {display: block;
    margin-left: auto;
    margin-right: auto;}
nav {
	background: linear-gradient(-45deg, #ee7752, #e73c7e, #2350d5, #23d5ab);
	background-size: 400% 400%;
	animation: gradient 15s ease infinite;
    margin-left: 18%;
    margin-right: 18%;
    border-radius: 15px;
}
.img-fluid {
    width: 300px;
    height: auto;
}
.resize-header {
    width: 80px;
}
header {
	background: linear-gradient(-45deg, #ee7752, #e73c7e, #2350d5, #23d5ab);
	background-size: 400% 400%;
	animation: gradient 15s ease infinite;
    line-height: 3.5em;
}

@keyframes gradient {
	0% {
		background-position: 0 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0 50%;
	}
}

.limit{
    font-size : 1.3vw;
    font-family: "Apple Symbols";
    color: #23d5d2 !important;
}

li {
    list-style-type: none;
}
</style>

<html lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        {% block header_logged_in%}
            <head>
                <title>WriteCloud-Home</title>
            </head>

            <header class="navbar navbar-default">
              <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li><img class="resize-header" src="{% static "Logo.png" %}"/></li>
                    <li ><a class="limit" href="{% url 'writecloud:index' %}">Home</a></li>
                    <li><a class="limit" href="{% url 'writecloud:create_story' %}">Start Story</a></li>
                    <li><a class="limit" href="{% url 'writecloud:continue_story' %}">Continue Story</a></li>
                    <li><a class="limit" href="{% url 'writecloud:top_stories' %}">Top Stories</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="limit" href="{% url 'writecloud:account' %}">My Account</a></li>
                    <li><a class="limit" href="{% url 'writecloud:logout' %}">Log Out</a></li>
                    <li><a class="limit" href="{% url 'writecloud:contact' %}">Contact Us</a></li>
                </ul>
              </div>
            </header>
        {% endblock %}

        {% block header_logged_out%}
            <header class="navbar navbar-default">
              <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li><img class="resize-header" src="{% static "Logo.png" %}"/></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="limit" href="{% url 'writecloud:signup' %}">Sign Up</a></li>
                    <li><a class="limit" href="{% url 'writecloud:contact' %}">Contact Us</a></li>
                </ul>
              </div>
            </header>
        {% endblock %}

        {% block header_logo%}
            <nav class="navbar navbar-expand-lg">
                <img class="img-fluid" src="{% static "Logo.png" %}"/>
            </nav>
        {% endblock %}



    <body>
        {% block body_block %}
        {% endblock %}
    </body>

    <footer>
        {% block footer_block %}
        {% endblock %}
    </footer>

</html>

templates/writecloud/contact.html
{% extends "writecloud/base.html" %}

<!DOCTYPE html>
{% load static %}
{% block header_logged_in %}
    {% endblock %}
    {% block body_block %}
<style>
.row{
    margin-top: 5%;
}

.inner{
    color: #23d5d2;
    font-size : 1.6vw;
    font-family: "Apple Symbols";
    display: flex;
    justify-content: center;
}

p {
    color: #ee7752;
    font-size : 1.6vw;
    font-family: "Apple Symbols";
    display: flex;
    justify-content: center;
}
</style>

     <div class="row">
            <p>We are the WriteCloud Team</p>
            <p class="inner">Matilda Bradley</p>
            <p class="inner">Marianna Marcelline</p>
            <p class="inner">Giorgio Ciacchella</p>
            <p class="inner">Kiril Bikov</p>
     </div>

    <div class="row">
            <p>Email </p>
            <p class="inner">team9duofg@gmail.com</p>
     </div>

{% endblock %} }}

templates/writecloud/createStory.html
{% extends "writecloud/base.html" %}

<!DOCTYPE html>
{% load static %}
{% block header_logged_out %}
{% endblock %}
{% block header_logo %}
{% endblock %}
{% block body_block %}
<style>

h5{
    margin-top: 1%;
    margin-left: 4%;
    margin-right: 20%;
    font-size : 1.6vw;
    font-family: "Apple Symbols";
    color: #ee7752;
    background-color: #f7ddd4;
    border-radius: 5px;
}

form{
    margin-left: 1.3%;
    margin-right: 23%;
    margin-bottom: 1% !important;
    outline: none;
    border:none;
}
input{
    font-size : 1.8vw;
    font-family: "Apple Symbols";
    border-radius: 5px;
    color: #23d5d2 !important;
}

#credentials{
    margin-top: 1% !important;
    color: #ee7752;
}

::placeholder{
    color: #ee7752 !important;
    font-size : 1.2vw;
    font-family: "Apple Symbols";
}

#in, #in1, #in2, #in3{
    box-shadow: 0 0 5px #ee7752;
    background-color: #f7ddd4;
    font-size : 1.2vw;
    border: none;
    margin-top: 2%;
}

#templates{
    margin-top: 5%;
    margin-left: 10%;
}
#single_template1{
    margin-right: 7%;
    border-radius: 15px;
    box-shadow: 0 0 5px #23d5d2;
}
#single_template2{
    margin-right: 7%;
    border-radius: 15px;
    box-shadow: 0 0 5px #23d5d2;
    background: #23d5d2;
}
#single_template3{
    margin-right: 7%;
    border-radius: 15px;
    box-shadow: 0 0 5px #ee7752;
}
#single_template4{
    margin-right: 7%;
    border-radius: 15px;
    box-shadow: 0 0 5px #ee7752;
    background: #ee7752;
}

textarea[id^="input1"]{
    border: none !important;
    background-color: white !important;
    color: #ee7752;
}

textarea[id^="input2"]::placeholder{
    color: #23d5d2 !important;
    font-size : 1.2vw;
    font-family: "Apple Symbols";
}

textarea[id^="input2"]{
    border: none !important;
    background-color: white !important;
     color: #23d5d2;
}

textarea[id^="input3"]::placeholder{
    color: #ee7752 !important;
    font-size : 1.2vw;
    font-family: "Apple Symbols";
}

textarea[id^="input3"]{
    border: none !important;
    background-color: #23d5d2 !important;
    color: #ee7752;
}

textarea[id^="input4"]::placeholder{
    color: #23d5d2 !important;
    font-size : 1.2vw !important;
    font-family: "Apple Symbols";
}

textarea[id^="input4"]{
    border: none !important;
    background-color: #ee7752 !important;
    color: #23d5d2;
}
</style>

<div class="row">
    <div class="col-md-2 col-sm-2 col-lg-2" id="credentials">
        <h5>Start a new story</h5>
    </div>
</div>
<div class="row">
    <form id="create_story" method="post"  action="{% url 'writecloud:create_story' %}">{% csrf_token %}
        <div class="form-group">
            <div class="row">
                <div class="col-md-2 col-sm-2 col-lg-2" id="credentials">
                    <input type="text" id="in1" name="title" class="form-control" placeholder="Enter Title" />
                </div>
                <div class="col-md-2 col-sm-2 col-lg-2" id="credentials">
                    <input type="text" id="in2"  name="subtitle" class="form-control" placeholder="Enter Subtitle"/>
                </div>
                <div class="col-md-2 col-sm-2 col-lg-2" id="credentials">
                    <input type="text" id="in3"  name="length" class="form-control" placeholder="Enter Number of Pages"/>
                </div>
                <div class="col-md-2 col-sm-2 col-lg-2" id="credentials">
                    <input readonly onclick="imagesFunction()" type="text" id="in" value="Click to include images"  name="include_images" class="form-control" placeholder="No Images included"/>
                </div>
            </div>
            <div class="row" id="templates">
                <div class="col-md-2 col-sm-2 col-lg-2" >
                </div>
                 <div id="single_template1" class="col-md-4 col-sm-4 col-lg-4">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-lg-12">
                              <div class="form-group">
                                  <textarea readonly class="form-control" placeholder="Begin your story with template 1"
                                            id="input1" name="template1" rows="10"></textarea>
                              </div>
                    </div>
                </div>
              </div>
              <div id="single_template3" class="col-md-4 col-sm-4 col-lg-4">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-lg-12">
                          <div class="form-group">
                              <textarea readonly class="form-control" placeholder="Begin your story with template 2"
                                        id="input2" name="template2" rows="10"></textarea>
                          </div>
                    </div>
                </div>
              </div>
            </div>
            <div class="row" id="templates">
                <div class="col-md-2 col-sm-2 col-lg-2" >
                </div>
                 <div id="single_template2" class="col-md-4 col-sm-4 col-lg-4">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-lg-12">
                              <div class="form-group">
                                  <textarea readonly class="form-control" placeholder="Begin your story with template 3"
                                            id="input3" name="template3" rows="10"></textarea>
                              </div>
                    </div>
                </div>
              </div>
              <div id="single_template4" class="col-md-4 col-sm-4 col-lg-4">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-lg-12">
                          <div class="form-group">
                              <textarea readonly class="form-control" placeholder="Begin your story with template 4"
                                            id="input4" name="template4"  rows="10"></textarea>
                          </div>
                    </div>
                </div>
              </div>
            </div>
            <div hidden id="upload" class="row">
                <button type="submit" id="in"  class="btn btn-primary pull-right"><a id="credentials">Create Story</a></button>
            </div>
        </div>
    </form>
</div>

<script>
{#Functions for selecting template on click event#}
document.getElementById("input1").addEventListener("click", ()=>{
    $('#input1').val('✓');
    $('#input2').val('');
    $('#input3').val('');
    $('#input4').val('');

});
document.getElementById("input2").addEventListener("click", ()=>{
    $('#input2').val('✓');
    $('#input1').val('');
    $('#input3').val('');
    $('#input4').val('');

});
document.getElementById("input3").addEventListener("click", ()=>{
    $('#input3').val('✓');
    $('#input1').val('');
    $('#input2').val('');
    $('#input4').val('');

});
document.getElementById("input4").addEventListener("click", ()=>{
    $('#input4').val('✓');
    $('#input1').val('');
    $('#input2').val('');
    $('#input3').val('');

});

{#Function for choosing an image or not on click event#}
let timesClicked = 0;
function imagesFunction(){
    timesClicked++;
    if (timesClicked%2 !== 0){
        $('input[name="include_images"]').val('Images Included');
    } else{
        $('input[name="include_images"]').val('');
    }
}
jQuery("#in1, #in2, #in3").on("input", function () {
    const isValid = validate();
    if (isValid) {
      jQuery("#upload").removeAttr("hidden");
    }
});

{#Allow only correct creation of story with present content#}
function validate() {
  let isValid = true;
  $('input').each(function() {
    if ($(this).val() === '')
        isValid = false;
    if ($(this).attr("id") === 'in3' && !$.isNumeric($(this).val()))
        isValid = false;
  });
  return isValid;
}
</script>

{% endblock %}

templates/writecloud/index.html
{% extends "writecloud/base.html" %}

<!DOCTYPE html>
{% block header_logged_out %}
    {% endblock %}
{% block body_block %}
{% load static %}

<style>
.row{
    margin-top: 1% !important;
    color: #ee7752;
}
.inside{
    font-size : 1.8vw;
    font-family: "Apple Symbols";
    color: #ee7752;
    background-color: #f7ddd4;
    border-radius: 5px;
}
.comment{
    font-size : 1.5vw;
    font-family: "Apple Symbols";
    color: #23d5d2;
    display: flex;
    justify-content: center;
}

::placeholder{
    font-size : 1.4vw;
    font-family: "Apple Symbols";
    color: #ee7752;
    font-weight: bold;
}

#input{
    background: #23d5d2;
    border-radius: 15px;
}

#rankings{
    margin: auto;
}

#left-comment{
    border-radius: 15px;
    box-shadow: 0 0 5px #23d5d2;
}

.glyphicon-star {
    color: #23d5d2;
}

</style>
    <div class="row">
        <div class="col-md-1 col-sm-1 col-lg-1" >
        </div>
      <div class="col-md-6 col-sm-6 col-lg-6">
        <div class="row">
            <li><a class="inside" href="{% url 'writecloud:create_story' %}">Start a new story</a></li>
        </div>
        <div class="row">
            <li><a class="inside" href="{% url 'writecloud:create_story' %}">Title</a></li>
        </div>
        <div class="row">
            <li><a class="inside" href="{% url 'writecloud:create_story' %}">Select a template</a></li>
        </div>
          <div class="row">
            <div class="col-md-8 col-sm-8 col-lg-8">
                  <div onclick="location.href='{% url 'writecloud:create_story' %}';">
                      <textarea class="form-control" readonly placeholder="Write new story to the cloud"
                                id="input" rows="6"></textarea>
                  </div>
            </div>
          </div>
      </div>
        <div class="col-md-1 col-sm-1 col-lg-1" >
        </div>
      <div class="col-md-5 col-sm-5 col-lg-5">
        <div class="row">
            <li><a class="inside" href="{% url 'writecloud:continue_story' %}">Continue a Progressing Story</a></li>
        </div>
        <div class="row">
            <li><a class="inside">{{ total_stories }} Stories</a></li>
        </div>
        <div class="row">
            <li><a class="inside">{{ total_users }} Users</a></li>
        </div>
        <div class="row">
            <div class="col-md-9 col-sm-9 col-lg-9">
                <form>
                  <div class="form-group" onclick="location.href='{% url 'writecloud:continue_story' %}';">
                      <textarea class="form-control" readonly placeholder="Click to choose a story from the cloud"
                                id="input" rows="6" ></textarea>
                  </div>
                </form>
            </div>
        </div>
      </div>
        <div class="col-md-1 col-sm-1 col-lg-1" >
        </div>
    </div>
    {% if stories|length > 0 %}
    <div class="row d-flex justify-content-center text-center" id="rankings">
            <li><a class="inside" href="#">Top {{ stories|length }} Stories</a></li>
    </div>
    {% endif %}
    {% for story in stories %}
    <div class="row">
        <div class="col-md-1 col-sm-1 col-lg-1">
        </div>
        <div class="col-md-3 col-sm-3 col-lg-3">
        <li><a href="{% url 'writecloud:story' story.uuid %}" class="inside">{{ forloop.counter }}. {{ story.title }}</a></li>
        </div>
        <div class="col-md-3 col-sm-3 col-lg-3" id="stars">
            <div class="row">
            <div class="rate">
                {% for star in story.stars|get_top_range %}
                    <div class="col-md-2 col-sm-2 col-lg-2">
                        <span class="glyphicon glyphicon-star"></span>
                    </div>
                {% endfor %}
            </div>
        </div>
        </div>
        <div class="col-md-3 col-sm-3 col-lg-3" id="left-comment">
            <li><a class="comment" href="{% url 'writecloud:story' story.uuid %}">{{ story.total_reviews }} Reviews</a></li>
        </div>
        <div class="col-md-1 col-sm-1 col-lg-1">
        </div>
    </div>
    {% endfor %}
{% endblock body_block%}

templates/writecloud/rankings.html
{% extends 'writecloud/base.html' %}

{% block head_block %}
    <h1>WriteCloud Top Stories</h1>
{% endblock %}

{% block body_block %}
    {% for story in stories %}
        <h2><a href="{% url 'writecloud:story' story.uuid %}">{{ story.title }}</a></h2>

        <p><b>{{ story.stars }} / 5</b><br />
        out of {{ story.total }} ratings</p>

        <br />
    {% endfor %}
{% endblock %}